Repository techeer-sv/graphy, pull requests merged in 2023-03, with the labels that each got.

#12 BE/#11 프로젝트 수정 기능 구현
  backend/src/main/java/com/graphy/backend/domain/project/controller/ProjectController.java
  backend/src/main/java/com/graphy/backend/domain/project/dto/ProjectDto.java
  backend/src/main/java/com/graphy/backend/domain/project/entity/Project.java
  backend/src/main/java/com/graphy/backend/domain/project/mapper/ProjectMapper.java
  backend/src/main/java/com/graphy/backend/domain/project/service/ProjectService.java
  backend/src/main/java/com/graphy/backend/global/result/ResultCode.java
Labels: 기능구현

#17 BE/#16 도메인 삭제 및 이동
  backend/src/main/java/com/graphy/backend/domain/project/entity/Project.java
  backend/src/main/java/com/graphy/backend/domain/project/entity/ProjectImage.java
  backend/src/main/java/com/graphy/backend/domain/projectimage/controller/ProjectImageController.java
  backend/src/main/java/com/graphy/backend/domain/projectimage/repository/ProjectImageRepository.java
  backend/src/main/java/com/graphy/backend/domain/projectimage/service/ProjectImageService.java
Labels: 리팩토링

#20 BE/#19 프로젝트 글 전체 조회 API
  .env.example
  backend/src/main/java/com/graphy/backend/domain/project/controller/ProjectController.java
  backend/src/main/java/com/graphy/backend/domain/project/dto/ProjectDto.java
  backend/src/main/java/com/graphy/backend/domain/project/repository/ProjectRepository.java
  backend/src/main/java/com/graphy/backend/domain/project/service/ProjectService.java
  backend/src/main/resources/application-dbconfig-example.yml
  backend/src/main/resources/application.yml
  docker-compose.yml
Labels: 기능구현

#22 BE/#14 프로젝트 글 생성 API
  backend/build.gradle
  backend/src/main/java/com/graphy/backend/domain/project/controller/ProjectController.java
  backend/src/main/java/com/graphy/backend/domain/project/dto/ProjectDto.java
  backend/src/main/java/com/graphy/backend/domain/project/mapper/ProjectMapper.java
  backend/src/main/java/com/graphy/backend/domain/project/service/ProjectService.java
  backend/src/main/java/com/graphy/backend/global/config/S3Config.java
  backend/src/main/resources/application-dbconfig-example.yml
  backend/src/main/resources/application.yml
Labels: 기능구현

#24 BE/#21 프로젝트 글의 내용 검색 기능 구현
  backend/src/main/java/com/graphy/backend/BackendApplication.java
  backend/src/main/java/com/graphy/backend/domain/project/controller/ProjectController.java
  backend/src/main/java/com/graphy/backend/domain/project/repository/ProjectRepository.java
  backend/src/main/java/com/graphy/backend/domain/project/service/ProjectService.java
Labels: 기능구현

#27 BE/#25 Tag 테이블 추가 및 이에 따른 전체적인 API 수정
  backend/src/main/java/com/graphy/backend/BackendApplication.java
  backend/src/main/java/com/graphy/backend/domain/comment/domain/Comment.java
  backend/src/main/java/com/graphy/backend/domain/comment/repository/CommentRepository.java
  backend/src/main/java/com/graphy/backend/domain/project/controller/ProjectController.java
  backend/src/main/java/com/graphy/backend/domain/project/domain/Project.java
  backend/src/main/java/com/graphy/backend/domain/project/domain/ProjectImage.java
  backend/src/main/java/com/graphy/backend/domain/project/domain/ProjectTag.java
  backend/src/main/java/com/graphy/backend/domain/project/domain/ProjectTags.java
  backend/src/main/java/com/graphy/backend/domain/project/domain/Tag.java
  backend/src/main/java/com/graphy/backend/domain/project/domain/Tags.java
  backend/src/main/java/com/graphy/backend/domain/project/dto/ProjectDto.java
  backend/src/main/java/com/graphy/backend/domain/project/mapper/ProjectMapper.java
  backend/src/main/java/com/graphy/backend/domain/project/repository/ProjectRepository.java
  backend/src/main/java/com/graphy/backend/domain/project/repository/ProjectTagRepository.java
  backend/src/main/java/com/graphy/backend/domain/project/repository/TagRepository.java
  backend/src/main/java/com/graphy/backend/domain/project/service/ProjectService.java
  backend/src/main/java/com/graphy/backend/global/common/FileUploader.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/data.sql
  backend/src/test/java/com/graphy/backend/domain/project/service/ProjectServiceTest.java
Labels: 기능구현

#33 test: 프로젝트 수정 API 테스트 코드 작성
  backend/src/test/java/com/graphy/backend/domain/project/controller/ProjectControllerTest.java
Labels: 테스트

#34 BE/#31 프로젝트 생성, 내용 검색 TEST 코드 추가
  backend/src/test/java/com/graphy/backend/domain/project/controller/ProjectIntegrationTest.java
Labels: 테스트

#43 BE/#37 썸네일 기능 추가
  backend/src/main/java/com/graphy/backend/domain/project/domain/Project.java
  backend/src/main/java/com/graphy/backend/domain/project/dto/ProjectDto.java
  backend/src/main/java/com/graphy/backend/domain/project/mapper/ProjectMapper.java
  backend/src/main/java/com/graphy/backend/domain/project/service/ProjectService.java
Labels: 기능구현

#44 BE/#42 예외처리를 위한 ErrorResponse 세팅
  backend/src/main/java/com/graphy/backend/domain/project/controller/ProjectController.java
  backend/src/main/java/com/graphy/backend/domain/project/dto/ProjectDto.java
  backend/src/main/java/com/graphy/backend/global/error/ErrorCode.java
  backend/src/main/java/com/graphy/backend/global/error/ErrorResponse.java
  backend/src/main/java/com/graphy/backend/global/error/GlobalExceptionHandler.java
  backend/src/main/java/com/graphy/backend/global/error/exception/BusinessException.java
Labels: 기타/세팅

#47 BE/#46 프로젝트 업데이트 예외처리
  backend/src/main/java/com/graphy/backend/domain/project/controller/ProjectController.java
  backend/src/main/java/com/graphy/backend/domain/project/domain/ProjectTag.java
  backend/src/main/java/com/graphy/backend/domain/project/dto/ProjectDto.java
  backend/src/main/java/com/graphy/backend/domain/project/service/ProjectService.java
Labels: 리팩토링

#40 Fe/#18 상단바 및 메인 페이지 퍼블리싱
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/assets/image/project.png
  frontend/src/assets/pencil-square.svg
  frontend/src/assets/person-circle.svg
  frontend/src/components/Banner.tsx
  frontend/src/components/NavBar.tsx
  frontend/src/components/ProjectCard.tsx
  frontend/src/pages/MainPage.tsx
  frontend/tailwind.config.cjs
  frontend/yarn.lock
Labels: 기능구현
