Repository techeer-sv/graphy, pull requests merged in 2023-06, with the labels that each got.

#120 Be/#114 신규 공고 API 구현
  .gitignore
  backend/build.gradle
  backend/src/main/java/com/graphy/backend/domain/job/controller/JobController.java
  backend/src/main/java/com/graphy/backend/domain/job/domain/Job.java
  backend/src/main/java/com/graphy/backend/domain/job/dto/JobDto.java
  backend/src/main/java/com/graphy/backend/domain/job/repository/JobRepository.java
  backend/src/main/java/com/graphy/backend/domain/job/service/JobService.java
  backend/src/main/java/com/graphy/backend/global/config/SchedulingConfig.java
  backend/src/main/java/com/graphy/backend/global/config/logaspect/LoggingAspect.java
  backend/src/test/java/com/graphy/backend/domain/job/controller/JobControllerTest.java
  backend/src/test/java/com/graphy/backend/domain/job/service/JobServiceTest.java
  logs/wetayo-logs-json.log
Labels: 기능구현

#135 Fe/#127 TypeScript 타입 지정
  frontend/service-worker.js
  frontend/src/Recoil.tsx
  frontend/src/components/ProjectCard.tsx
  frontend/src/components/PutReply.tsx
  frontend/src/components/ReadReReply.tsx
  frontend/src/components/ReadReply.tsx
  frontend/src/components/Reply.tsx
  frontend/src/components/WriteReReply.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/ReadingPage.tsx
  frontend/src/test/components/ImageUploader.test.tsx
  frontend/src/test/components/NavBar.test.tsx
  frontend/src/test/components/ProjectCard.test.tsx
  frontend/src/test/components/PutReply.test.tsx
  frontend/src/test/components/QuillEditor.test.tsx
  frontend/src/test/components/QuillWritten.test.tsx
  frontend/src/test/components/ReadReReply.test.tsx
  frontend/src/test/components/ReadReply.test.tsx
  frontend/src/test/components/Reply.test.tsx
  frontend/src/test/components/TechStackSelection.test.tsx
  frontend/src/test/components/WriteReReply.test.tsx
  frontend/src/test/jest/RecoilObserver.tsx
  frontend/src/test/pages/MainPage.test.tsx
  frontend/src/test/pages/ModifyingPage.test.tsx
  frontend/src/test/pages/WritingPage.test.tsx
Labels: 리팩토링

#137 Fe/#134 로그인, 회원가입 페이지 퍼블리싱
  frontend/.dockerignore
  frontend/.gitignore
  frontend/src/App.tsx
  frontend/src/assets/image/email.svg
  frontend/src/pages/SigninPage.tsx
  frontend/src/pages/SignupPage.tsx
Labels: 퍼블리싱

#140 Fe/#138 메인페이지 무한 스크롤 기능구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/test/pages/MainPage.test.tsx
  frontend/yarn.lock
Labels: 기능구현

#139 Be/#133 Spring Security + JWT를 통한 인증 및 인가 세팅
  backend/build.gradle
  backend/src/main/java/com/graphy/backend/domain/comment/service/CommentService.java
  backend/src/main/java/com/graphy/backend/domain/member/controller/MemberController.java
  backend/src/main/java/com/graphy/backend/domain/member/domain/Member.java
  backend/src/main/java/com/graphy/backend/domain/member/domain/Role.java
  backend/src/main/java/com/graphy/backend/domain/member/dto/MemberDto.java
  backend/src/main/java/com/graphy/backend/domain/member/repository/MemberRepository.java
  backend/src/main/java/com/graphy/backend/domain/member/service/MemberService.java
  backend/src/main/java/com/graphy/backend/domain/project/controller/ProjectController.java
  backend/src/main/java/com/graphy/backend/domain/project/service/ProjectService.java
  backend/src/main/java/com/graphy/backend/global/auth/jwt/CustomUserDetailsService.java
  backend/src/main/java/com/graphy/backend/global/auth/jwt/JwtFilter.java
  backend/src/main/java/com/graphy/backend/global/auth/jwt/TokenProvider.java
  backend/src/main/java/com/graphy/backend/global/auth/jwt/dto/TokenInfo.java
  backend/src/main/java/com/graphy/backend/global/config/SecurityConfig.java
  backend/src/main/java/com/graphy/backend/global/config/SwaggerConfig.java
  backend/src/main/java/com/graphy/backend/global/error/ErrorCode.java
  backend/src/main/java/com/graphy/backend/global/result/ResultCode.java
  backend/src/test/java/com/graphy/backend/domain/member/controller/MemberControllerTest.java
  backend/src/test/java/com/graphy/backend/domain/member/domain/MemberTest.java
  backend/src/test/java/com/graphy/backend/domain/member/service/MemberServiceTest.java
Labels: 기타/세팅, 기능구현

#145 Fe/#141 마이페이지 퍼블리싱 및 반응형
  frontend/src/App.tsx
  frontend/src/assets/fonts/LatoBold.ttf
  frontend/src/assets/fonts/LatoLight.ttf
  frontend/src/assets/fonts/LatoRegular.ttf
  frontend/src/assets/fonts/LatoSemibold.ttf
  frontend/src/assets/image/Like.svg
  frontend/src/assets/image/graphyIcon.png
  frontend/src/assets/image/myProfile.png
  frontend/src/assets/image/profileIcon.svg
  frontend/src/components/NavBar.tsx
  frontend/src/index.css
  frontend/src/pages/MyPage.tsx
  frontend/tailwind.config.cjs
Labels: 퍼블리싱

#146 feat: 팔로워&팔로잉 퍼블리싱
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/image/closeIcon.svg
  frontend/src/assets/image/followerIcon.svg
  frontend/src/assets/image/followingIcon.svg
  frontend/src/components/FollowModal.tsx
  frontend/src/pages/MyPage.tsx
  frontend/yarn.lock
Labels: 퍼블리싱
