Repository techeer-sv/graphy, pull requests merged in 2023-10, with the labels that each got.

#233 BE/#224 팔로우 시, 팔로우한 사용자에게 알림 전송 기능 구현
  backend/src/main/java/com/graphy/backend/domain/follow/service/FollowService.java
  backend/src/main/java/com/graphy/backend/domain/notification/domain/Notification.java
  backend/src/main/java/com/graphy/backend/domain/notification/domain/NotificationType.java
  backend/src/main/java/com/graphy/backend/domain/notification/dto/NotificationDto.java
  backend/src/main/java/com/graphy/backend/domain/notification/repository/NotificationRepository.java
  backend/src/main/java/com/graphy/backend/domain/notification/service/NotificationService.java
  backend/src/main/java/com/graphy/backend/global/error/ErrorCode.java
  backend/src/test/java/com/graphy/backend/domain/follow/service/FollowServiceTest.java
Labels: 기능구현

#228 feat : Recruitment 도메인 CRUD 구현
  backend/src/main/java/com/graphy/backend/domain/project/domain/Project.java
  backend/src/main/java/com/graphy/backend/domain/project/domain/ProjectTag.java
  backend/src/main/java/com/graphy/backend/domain/project/domain/Tag.java
  backend/src/main/java/com/graphy/backend/domain/project/service/ProjectService.java
  backend/src/main/java/com/graphy/backend/domain/project/service/TagService.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/controller/RecruitmentController.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/domain/Recruitment.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/domain/RecruitmentTag.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/domain/RecruitmentTags.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/dto/request/CreateRecruitmentRequest.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/dto/request/UpdateRecruitmentRequest.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/dto/response/GetRecruitmentDetailResponse.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/dto/response/GetRecruitmentResponse.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/repository/RecruitmentCustomRepository.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/repository/RecruitmentRepository.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/repository/RecruitmentTagRepository.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/repository/custom/RecruitmentCustomRepositoryImpl.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/service/RecruitmentService.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/service/RecruitmentTagService.java
  backend/src/main/java/com/graphy/backend/global/common/BaseEntity.java
  backend/src/main/java/com/graphy/backend/global/error/ErrorCode.java
  backend/src/main/java/com/graphy/backend/global/error/GlobalExceptionHandler.java
  backend/src/main/java/com/graphy/backend/global/error/exception/InvalidMemberException.java
  backend/src/main/java/com/graphy/backend/global/result/ResultCode.java
  backend/src/main/resources/tag.txt
  backend/src/test/java/com/graphy/backend/domain/project/service/ProjectServiceTest.java
  backend/src/test/java/com/graphy/backend/domain/recruitment/controller/RecruitmentControllerTest.java
  backend/src/test/resources/application-test.yml
Labels: 기능구현

#232 FE/#231 프로젝트 검색 페이지 마이그레이션
  frontend/src/app/(search)/search-post/[postName]/page.tsx
  frontend/src/app/(search)/search-post/page.tsx
  frontend/src/app/(search)/search-user/[userName]/page.tsx
Labels: 기능구현

#237 BE/#236 프로젝트 참가 신청 기능 구현
  backend/src/main/java/com/graphy/backend/domain/recruitment/controller/ApplicationController.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/domain/Application.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/domain/ApplicationTag.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/domain/ApplicationTags.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/dto/request/CreateApplicationRequest.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/dto/request/TechLevelDto.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/service/ApplicationService.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/service/RecruitmentService.java
  backend/src/main/java/com/graphy/backend/global/result/ResultCode.java
Labels: 기능구현

#246 BE/#245 쪽지 상제 조회 기능 구현
  backend/src/main/java/com/graphy/backend/domain/message/controller/MessageController.java
  backend/src/main/java/com/graphy/backend/domain/message/domain/Message.java
  backend/src/main/java/com/graphy/backend/domain/message/dto/response/GetMessageDetailResponse.java
  backend/src/main/java/com/graphy/backend/domain/message/service/MessageService.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/service/ApplicationService.java
  backend/src/main/java/com/graphy/backend/global/error/ErrorCode.java
  backend/src/main/java/com/graphy/backend/global/result/ResultCode.java
Labels: 기능구현

#250 BE/#249 Service 계층 @Transactional 설정
  backend/src/main/java/com/graphy/backend/domain/message/service/MessageService.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/service/ApplicationService.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/service/RecruitmentService.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/service/RecruitmentTagService.java
Labels: 리팩토링

#248 BE/#247 프로젝트 참가 중복 신청 방지 로직 추가
  backend/src/main/java/com/graphy/backend/domain/recruitment/repository/ApplicationRepository.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/service/ApplicationService.java
  backend/src/main/java/com/graphy/backend/global/error/ErrorCode.java
  backend/src/main/java/com/graphy/backend/global/error/exception/InvalidMemberException.java
Labels: 리팩토링

#254 BE/#235 알림 발생 시 이메일 전송 기능 추가
  backend/build.gradle
  backend/src/main/java/com/graphy/backend/domain/notification/domain/Notification.java
  backend/src/main/java/com/graphy/backend/domain/notification/dto/NotificationDto.java
  backend/src/main/java/com/graphy/backend/domain/notification/service/MailingService.java
  backend/src/main/java/com/graphy/backend/domain/notification/service/NotificationService.java
  backend/src/main/java/com/graphy/backend/global/config/AsyncConfig.java
  backend/src/main/java/com/graphy/backend/global/config/JavaMailConfig.java
  backend/src/main/java/com/graphy/backend/global/error/ErrorCode.java
  backend/src/main/resources/static/images/image-1.png
  backend/src/main/resources/static/images/image-2.png
  backend/src/main/resources/templates/email/index.html
Labels: 기능구현

#234 Be/#206 신입/인턴 채용공고 크롤링 기능 구현
  backend/src/main/java/com/graphy/backend/domain/job/domain/Job.java
  crawling_python/Dockerfile
  crawling_python/crawling_jobkorea.py
  crawling_python/crawling_saramin.py
  crawling_python/global_utils.py
  crawling_python/requirements.txt
  crawling_python/scheduler.py
Labels: 기능구현

#258 BE/#257 프로젝트 목록 조회 시 검색이 제대로 되지 않는 오류 수정
  backend/src/main/java/com/graphy/backend/domain/project/dto/request/GetProjectsRequest.java
  backend/src/main/java/com/graphy/backend/domain/project/repository/custom/ProjectCustomRepositoryImpl.java
  backend/src/main/java/com/graphy/backend/global/common/PageRequest.java
  backend/src/main/java/com/graphy/backend/global/error/GlobalExceptionHandler.java
Labels: 오류 수정

#259 BE/#255 알림 목록 조회 기능 구현
  backend/src/main/java/com/graphy/backend/domain/notification/controller/NotificationController.java
  backend/src/main/java/com/graphy/backend/domain/notification/domain/Notification.java
  backend/src/main/java/com/graphy/backend/domain/notification/dto/response/GetNotificationResponse.java
  backend/src/main/java/com/graphy/backend/domain/notification/repository/NotificationRepository.java
  backend/src/main/java/com/graphy/backend/domain/notification/service/NotificationService.java
  backend/src/main/java/com/graphy/backend/global/result/ResultCode.java
Labels: 기능구현

#262 Fe/#223 WritingPage 및 ImageUploader, TechStackSelection, QuillEditor 컴포넌트 마이그레이션
  frontend/.env.local.example
  frontend/next.config.js
  frontend/package.json
  frontend/public/css/toastui-editor.css
  frontend/src/app/(submit)/new-post/page.tsx
  frontend/src/app/api/v1/s3/route.ts
  frontend/src/components/example.tsx
  frontend/src/components/submit/imageUploader.tsx
  frontend/src/components/submit/techStackSelection.tsx
  frontend/src/components/submit/toastUIEditor.tsx
  frontend/src/utils/atoms.ts
  frontend/src/utils/s3config.ts
  frontend/yarn.lock
Labels: 기능구현

#264 Fe/#263 글 수정 페이지 마이그레이션
  frontend/src/app/(submit)/modification/page.tsx
Labels: 기능구현

#260 Be/#253 마감기한지난 채용공고 삭제 로직 구현
  crawling_python/global_utils.py
  crawling_python/scheduler.py
Labels: 기능구현

#266 feat : NavBar 마이그레이션
  frontend/src/app/layout.tsx
  frontend/src/components/general/NavBar.tsx
Labels: 기능구현

#267 Be/#261 채용공고 목록 조회 기능 구현
  backend/src/main/java/com/graphy/backend/domain/job/controller/JobController.java
  backend/src/main/java/com/graphy/backend/domain/job/dto/JobDto.java
  backend/src/main/java/com/graphy/backend/domain/job/dto/response/GetJobResponse.java
  backend/src/main/java/com/graphy/backend/domain/job/repository/JobRepository.java
  backend/src/main/java/com/graphy/backend/domain/job/service/JobService.java
  backend/src/main/java/com/graphy/backend/global/common/PageRequest.java
  backend/src/main/java/com/graphy/backend/global/error/ErrorCode.java
  backend/src/main/java/com/graphy/backend/global/result/ResultCode.java
  backend/src/test/java/com/graphy/backend/domain/job/controller/JobControllerTest.java
  backend/src/test/java/com/graphy/backend/domain/job/service/JobServiceTest.java
Labels: 기능구현

#275 feat : 사용자 닉네임으로 마이 페이지 조회 기능 구현
  backend/src/main/java/com/graphy/backend/domain/member/controller/MemberController.java
  backend/src/main/java/com/graphy/backend/domain/member/repository/MemberRepository.java
  backend/src/main/java/com/graphy/backend/domain/member/service/MemberService.java
  backend/src/main/java/com/graphy/backend/domain/project/dto/response/GetProjectInfoResponse.java
  backend/src/main/java/com/graphy/backend/domain/project/service/ProjectService.java
  backend/src/main/java/com/graphy/backend/global/config/SecurityConfig.java
  backend/src/test/java/com/graphy/backend/domain/member/controller/MemberControllerTest.java
  backend/src/test/java/com/graphy/backend/domain/project/service/ProjectServiceTest.java
Labels: 기능구현

#273 Fe/#243 ReadingPage 및 GptModal, Reply, QuillWritten, ReadReply, ReadReReply, WritingReReply, PutReReply 컴포넌트 마이그레이션
  frontend/package.json
  frontend/src/app/(read)/post/[postId]/page.tsx
  frontend/src/app/(read)/post/[title]/page.tsx
  frontend/src/app/(search)/search-post/[postName]/page.tsx
  frontend/src/app/(search)/search-user/[userName]/page.tsx
  frontend/src/app/page.tsx
  frontend/src/components/main/ProjectCard.tsx
  frontend/src/components/read/GptModal.tsx
  frontend/src/components/read/PutReply.tsx
  frontend/src/components/read/ReadReReply.tsx
  frontend/src/components/read/ReadReply.tsx
  frontend/src/components/read/Reply.tsx
  frontend/src/components/read/ToastViewer.tsx
  frontend/src/components/read/WriteReReply.tsx
  frontend/src/utils/atoms.ts
  frontend/yarn.lock
Labels: 기능구현

#276 BE/#270 프로젝트 상세 조회 시, 조회수 증가 구현
  backend/src/main/java/com/graphy/backend/domain/comment/domain/Bookmark.java
  backend/src/main/java/com/graphy/backend/domain/job/controller/JobController.java
  backend/src/main/java/com/graphy/backend/domain/message/controller/MessageController.java
  backend/src/main/java/com/graphy/backend/domain/notification/controller/NotificationController.java
  backend/src/main/java/com/graphy/backend/domain/notification/service/NotificationService.java
  backend/src/main/java/com/graphy/backend/domain/project/controller/ProjectController.java
  backend/src/main/java/com/graphy/backend/domain/project/domain/Project.java
  backend/src/main/java/com/graphy/backend/domain/project/service/ProjectService.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/controller/RecruitmentController.java
  backend/src/main/java/com/graphy/backend/global/common/dto/PageRequest.java
  backend/src/test/java/com/graphy/backend/domain/project/service/ProjectServiceTest.java
  backend/src/test/resources/schema.sql
Labels: 기능구현
