Repository techeer-sv/graphy, pull requests merged in 2023-04, with the labels that each got.

#53 BE/#51 프로젝트 조회 API 예외처리
  backend/src/main/java/com/graphy/backend/domain/project/controller/ProjectController.java
Labels: 리팩토링

#50 Fe/#35 글쓰기 페이지 기능구현
  .env.example
  backend/src/main/resources/application.yml
  frontend/.dockerignore
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Recoil.tsx
  frontend/src/components/ImageUploader.tsx
  frontend/src/components/QuillEditor.tsx
  frontend/src/components/QuillWritten.tsx
  frontend/src/components/TechStackSelection.tsx
  frontend/src/pages/ReadingPage.tsx
  frontend/src/pages/WritingPage.tsx
  frontend/src/s3config.tsx
  frontend/tsconfig.json
  frontend/vite.config.ts
  frontend/yarn.lock
Labels: 기능구현

#58 BE/#57 검색 API 리팩토링
  backend/src/main/java/com/graphy/backend/domain/project/controller/ProjectController.java
  backend/src/main/java/com/graphy/backend/domain/project/dto/ProjectDto.java
  backend/src/main/java/com/graphy/backend/domain/project/repository/ProjectRepository.java
  backend/src/main/java/com/graphy/backend/domain/project/service/ProjectService.java
  backend/src/main/java/com/graphy/backend/domain/project/util/ProjectSpecification.java
  backend/src/main/java/com/graphy/backend/global/config/WebConfig.java
  backend/src/test/java/com/graphy/backend/domain/project/controller/ProjectIntegrationTest.java
Labels: 리팩토링

#60 BE/#59 Tag 테이블 insert 로직
  backend/src/main/java/com/graphy/backend/domain/project/service/ProjectService.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/data.sql
  backend/src/main/resources/tag.txt
Labels: 기타/세팅

#62 BE/#61 NGINX docker 세팅
  docker-compose.yml
  nginx/dockerfile
  nginx/nginx.conf
Labels: 기타/세팅

#65 BE/#64 Comment Entity 세팅
  backend/src/main/java/com/graphy/backend/domain/comment/controller/CommentController.java
  backend/src/main/java/com/graphy/backend/domain/comment/domain/Comment.java
  backend/src/main/java/com/graphy/backend/domain/comment/service/CommentService.java
Labels: 기타/세팅

#67 BE/#66 댓글(대댓글 포함) 조회 기능 구현
  backend/src/main/java/com/graphy/backend/domain/comment/controller/CommentController.java
  backend/src/main/java/com/graphy/backend/domain/comment/dto/CommentDto.java
  backend/src/main/java/com/graphy/backend/domain/project/domain/Project.java
  backend/src/main/java/com/graphy/backend/domain/project/dto/ProjectDto.java
  backend/src/main/java/com/graphy/backend/domain/project/mapper/ProjectMapper.java
Labels: 기능구현

#70 BE/#69 댓글 생성 API 구현
  backend/src/main/java/com/graphy/backend/domain/comment/controller/CommentController.java
  backend/src/main/java/com/graphy/backend/domain/comment/domain/Comment.java
  backend/src/main/java/com/graphy/backend/domain/comment/dto/CommentDto.java
  backend/src/main/java/com/graphy/backend/domain/comment/service/CommentService.java
  backend/src/main/java/com/graphy/backend/domain/project/domain/Project.java
  backend/src/main/java/com/graphy/backend/global/error/ErrorCode.java
  backend/src/main/java/com/graphy/backend/global/result/ResultCode.java
  backend/src/test/java/com/graphy/backend/domain/comment/service/CommentServiceTest.java
Labels: 기능구현, 테스트

#79 BE/#76 SonarQube 세팅
  .gitignore
  backend/Dockerfile
  backend/build.gradle
  backend/gradle.properties
Labels: 기타/세팅

#81 BE/#80 게시물 글자수 제한 변경
  backend/src/main/java/com/graphy/backend/domain/project/domain/Project.java
Labels: 기능구현
