Repository techeer-sv/graphy, pull requests merged in 2023-07, with the labels that each got.

#151 Fe/#142 회원가입, 로그인 기능 구현
  frontend/.eslintrc.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Recoil.tsx
  frontend/src/components/Banner.tsx
  frontend/src/components/ImageUploader.tsx
  frontend/src/components/NavBar.tsx
  frontend/src/components/PutReply.tsx
  frontend/src/components/QuillEditor.tsx
  frontend/src/components/ReadReReply.tsx
  frontend/src/components/ReadReply.tsx
  frontend/src/components/Reply.tsx
  frontend/src/components/WriteReReply.tsx
  frontend/src/pages/ModifyingPage.tsx
  frontend/src/pages/ReadingPage.tsx
  frontend/src/pages/SigninPage.tsx
  frontend/src/pages/SignupPage.tsx
  frontend/src/pages/WritingPage.tsx
  frontend/src/test/components/Reply.test.tsx
  frontend/src/test/pages/ReadingPage.test.tsx
  frontend/yarn.lock
Labels: 기능구현

#163 BE/#158 마이페이지 기능 구현
  backend/src/main/java/com/graphy/backend/domain/follow/service/FollowService.java
  backend/src/main/java/com/graphy/backend/domain/member/controller/MemberController.java
  backend/src/main/java/com/graphy/backend/domain/member/domain/Member.java
  backend/src/main/java/com/graphy/backend/domain/member/dto/MemberDto.java
  backend/src/main/java/com/graphy/backend/domain/member/repository/MemberRepository.java
  backend/src/main/java/com/graphy/backend/domain/member/service/MemberService.java
  backend/src/main/java/com/graphy/backend/domain/project/dto/ProjectDto.java
  backend/src/main/java/com/graphy/backend/domain/project/mapper/ProjectMapper.java
  backend/src/main/java/com/graphy/backend/domain/project/repository/ProjectRepository.java
  backend/src/main/java/com/graphy/backend/domain/project/service/ProjectService.java
  backend/src/main/java/com/graphy/backend/global/result/ResultCode.java
Labels: 기능구현

#169 Be/#167 Redis를 통한 Refresh Token 관리 기능 구현
  backend/build.gradle
  backend/src/main/java/com/graphy/backend/domain/follow/service/FollowService.java
  backend/src/main/java/com/graphy/backend/domain/member/controller/MemberController.java
  backend/src/main/java/com/graphy/backend/domain/member/dto/MemberDto.java
  backend/src/main/java/com/graphy/backend/domain/member/service/MemberService.java
  backend/src/main/java/com/graphy/backend/global/auth/jwt/JwtFilter.java
  backend/src/main/java/com/graphy/backend/global/auth/jwt/TokenProvider.java
  backend/src/main/java/com/graphy/backend/global/auth/jwt/dto/TokenDto.java
  backend/src/main/java/com/graphy/backend/global/auth/jwt/dto/TokenInfo.java
  backend/src/main/java/com/graphy/backend/global/auth/redis/domain/RefreshToken.java
  backend/src/main/java/com/graphy/backend/global/auth/redis/repository/RefreshTokenRepository.java
  backend/src/main/java/com/graphy/backend/global/common/Helper.java
  backend/src/main/java/com/graphy/backend/global/config/RedisConfig.java
  backend/src/main/java/com/graphy/backend/global/config/SecurityConfig.java
  backend/src/main/java/com/graphy/backend/global/error/ErrorCode.java
  backend/src/main/java/com/graphy/backend/global/error/GlobalExceptionHandler.java
  backend/src/main/java/com/graphy/backend/global/error/exception/AlreadyExistException.java
  backend/src/main/java/com/graphy/backend/global/result/ResultCode.java
  backend/src/test/java/com/graphy/backend/domain/comment/service/CommentServiceTest.java
  backend/src/test/java/com/graphy/backend/domain/follow/service/FollowServiceTest.java
  backend/src/test/java/com/graphy/backend/domain/member/controller/MemberControllerTest.java
  backend/src/test/java/com/graphy/backend/domain/member/service/MemberServiceTest.java
  backend/src/test/java/com/graphy/backend/domain/project/controller/ProjectControllerTest.java
  backend/src/test/java/com/graphy/backend/domain/project/service/ProjectServiceTest.java
Labels: 기능구현

#176 BE/# 175 MyPage API 에러 수정
  backend/src/main/java/com/graphy/backend/domain/comment/dto/CommentDto.java
  backend/src/main/java/com/graphy/backend/domain/job/dto/JobDto.java
  backend/src/main/java/com/graphy/backend/domain/member/controller/MemberController.java
  backend/src/main/java/com/graphy/backend/domain/member/dto/MemberDto.java
  backend/src/main/java/com/graphy/backend/domain/member/service/MemberService.java
  backend/src/main/java/com/graphy/backend/domain/project/dto/ProjectDto.java
Labels: 오류 수정

#178 Be/#174 부하 테스트 파일 추가
  backend/src/main/java/com/graphy/backend/domain/comment/repository/CommentRepository.java
  backend/src/main/resources/load-test.js
Labels: 기타/세팅
