Repository techeer-sv/graphy, pull requests merged in 2023-11, with the labels that each got.

#271 Be/#269 Prometheus + Grafana 연동
  backend/build.gradle
  backend/src/main/resources/application.yml
  datasource.yml
  docker-compose.yml
  prometheus/prometheus.yml
Labels: 기타/세팅

#283 BE/#282 구인 게시글 조회 및 상세 조회 API 권한 수정
  backend/src/main/java/com/graphy/backend/global/config/SecurityConfig.java
Labels: 리팩토링

#285 Be/#284 토큰 재발급 API 리팩토링
  backend/src/main/java/com/graphy/backend/domain/auth/controller/AuthController.java
  backend/src/main/java/com/graphy/backend/domain/auth/infra/TokenProvider.java
  backend/src/main/java/com/graphy/backend/domain/auth/service/AuthService.java
  backend/src/main/java/com/graphy/backend/global/config/SecurityConfig.java
  backend/src/test/java/com/graphy/backend/domain/auth/controller/AuthControllerTest.java
  backend/src/test/java/com/graphy/backend/domain/auth/service/AuthServiceTest.java
Labels: 리팩토링

#292 BE/#291 더미 데이터 저장 기능 구현
  backend/src/main/java/com/graphy/backend/domain/member/domain/Member.java
  backend/src/main/java/com/graphy/backend/domain/project/domain/ProjectImage.java
  backend/src/main/java/com/graphy/backend/domain/project/dto/response/GetProjectDetailResponse.java
  backend/src/main/java/com/graphy/backend/domain/project/service/ProjectService.java
  backend/src/main/java/com/graphy/backend/domain/project/util/ProjectInitializer.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/controller/RecruitmentController.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/domain/Recruitment.java
Labels: 기능구현

#289 Be/#288 MyPage API 수정
  backend/src/main/java/com/graphy/backend/domain/member/dto/response/GetMyPageResponse.java
  backend/src/test/java/com/graphy/backend/domain/member/controller/MemberControllerTest.java
Labels: 리팩토링

#297 BE/#296 구인 게시글 중복 조회 오류 수정
  backend/src/main/java/com/graphy/backend/domain/recruitment/repository/custom/RecruitmentCustomRepositoryImpl.java
Labels: 오류 수정

#300 BE/#299 구인 게시글에 조회수 기능 추가
  backend/src/main/java/com/graphy/backend/domain/recruitment/controller/RecruitmentController.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/domain/Recruitment.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/dto/response/GetRecruitmentDetailResponse.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/service/RecruitmentService.java
Labels: 기능구현

#298 구인공고 리스트 API 모집여부 출력 및 모집 중 필터링 추가
  backend/src/main/java/com/graphy/backend/domain/recruitment/controller/RecruitmentController.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/domain/Recruitment.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/dto/request/UpdateRecruitmentRequest.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/dto/response/GetRecruitmentDetailResponse.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/dto/response/GetRecruitmentResponse.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/repository/RecruitmentCustomRepository.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/repository/custom/RecruitmentCustomRepositoryImpl.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/service/RecruitmentService.java
Labels: 기능구현

#302 BE/# 301 구인 게시글 조회 API 키워드로 검색 안 되는 에러 수정
  backend/src/main/java/com/graphy/backend/domain/recruitment/repository/custom/RecruitmentCustomRepositoryImpl.java
Labels: 오류 수정

#304 BE/#303 CI 에러 수정
  backend/src/main/java/com/graphy/backend/domain/recruitment/repository/custom/RecruitmentCustomRepositoryImpl.java
  backend/src/test/java/com/graphy/backend/domain/project/controller/ProjectIntegrationTest.java
Labels: 오류 수정

#308 Be/#307 QueryDSL을 사용한 API에서 createdAt으로 정렬안되는 오류 수정
  backend/src/main/java/com/graphy/backend/domain/project/repository/custom/ProjectCustomRepositoryImpl.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/repository/custom/RecruitmentCustomRepositoryImpl.java
  backend/src/main/java/com/graphy/backend/global/util/QueryDslUtil.java
Labels: 오류 수정, 기능구현

#305 Fe/#290 프로젝트 구인 목록 페이지 퍼블리싱 및 알림기능 구현
  frontend/.eslintrc.json
  frontend/package.json
  frontend/public/images/svg/tag_x.svg
  frontend/src/app/page.tsx
  frontend/src/app/project/(read)/post/[postId]/page.tsx
  frontend/src/app/project/page.tsx
  frontend/src/app/recruitment/page.tsx
  frontend/src/components/general/ProjectNavBar.tsx
  frontend/src/components/general/RecruitmentNavBar.tsx
  frontend/src/components/recruitment/main/Filter.tsx
  frontend/src/components/recruitment/main/MultipleFilter.tsx
  frontend/src/components/recruitment/main/RecruitmentCard.tsx
  frontend/src/components/recruitment/main/SortToggleButton.tsx
  frontend/src/components/recruitment/main/ToggleButton.tsx
  frontend/src/components/recruitment/noticification/NoticeModal.tsx
  frontend/src/components/recruitment/noticification/Noticification.tsx
  frontend/src/utils/atoms.ts
  frontend/src/utils/stacks.ts
  frontend/src/utils/types.ts
  frontend/tailwind.config.cjs
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: 스타일, 기능구현, 퍼블리싱

#309 FE/#287 신규 공고 페이지 퍼블리싱
  frontend/src/app/recruitment/announcement/page.tsx
  frontend/src/components/recruitment/announcement/AnnouncementCard.tsx
  frontend/src/utils/atoms.ts
  frontend/src/utils/types.ts
Labels: 스타일, 기능구현, 퍼블리싱

#310 FE/#306 메인 페이지 프로젝트 랭킹 기능 추가
  frontend/.eslintrc.json
  frontend/package.json
  frontend/src/app/project/page.tsx
  frontend/tailwind.config.cjs
  frontend/yarn.lock
Labels: 스타일, 기능구현, 퍼블리싱
