Repository techeer-sv/graphy, pull requests merged in 2023-08, with the labels that each got.

#182 BE/#181 답글 조회 API QueryDSL로 리팩토링
  backend/src/main/java/com/graphy/backend/domain/comment/controller/CommentController.java
  backend/src/main/java/com/graphy/backend/domain/comment/dto/CommentDto.java
  backend/src/main/java/com/graphy/backend/domain/comment/dto/CommentWithMaskingDto.java
  backend/src/main/java/com/graphy/backend/domain/comment/dto/ReplyListDto.java
  backend/src/main/java/com/graphy/backend/domain/comment/repository/CommentCustomRepository.java
  backend/src/main/java/com/graphy/backend/domain/comment/repository/CommentCustomRepositoryImpl.java
  backend/src/main/java/com/graphy/backend/domain/comment/repository/CommentRepository.java
  backend/src/main/java/com/graphy/backend/domain/comment/service/CommentService.java
  backend/src/main/java/com/graphy/backend/domain/project/dto/ProjectDto.java
  backend/src/main/java/com/graphy/backend/domain/project/mapper/ProjectMapper.java
  backend/src/main/java/com/graphy/backend/domain/project/service/ProjectService.java
Labels: 리팩토링

#180 BE/# 179 테스트 코드 에러 수정
  backend/src/main/java/com/graphy/backend/domain/member/service/MemberService.java
  backend/src/test/java/com/graphy/backend/domain/follow/controller/FollowControllerTest.java
  backend/src/test/java/com/graphy/backend/domain/follow/service/FollowServiceTest.java
  backend/src/test/java/com/graphy/backend/domain/job/controller/JobControllerTest.java
  backend/src/test/java/com/graphy/backend/domain/member/controller/MemberControllerTest.java
Labels: 오류 수정

#164 Fe/#162 글 작성자 표시 및 유저 검색 기능 구현
  frontend/src/App.tsx
  frontend/src/assets/image/searchIcon.png
  frontend/src/components/NavBar.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/ReadingPage.tsx
  frontend/src/pages/SearchProjectPage.tsx
  frontend/src/pages/SearchUserPage.tsx
Labels: 기능구현

#187 Be/#185 Comment 도메인 리팩토링 및 테스트 코드 수정
  backend/Dockerfile
  backend/src/main/java/com/graphy/backend/domain/comment/controller/CommentController.java
  backend/src/main/java/com/graphy/backend/domain/comment/dto/CommentDto.java
  backend/src/main/java/com/graphy/backend/domain/comment/dto/request/CreateCommentRequest.java
  backend/src/main/java/com/graphy/backend/domain/comment/dto/request/UpdateCommentRequest.java
  backend/src/main/java/com/graphy/backend/domain/comment/dto/response/CreateCommentResponse.java
  backend/src/main/java/com/graphy/backend/domain/comment/dto/response/GetCommentWithMaskingResponse.java
  backend/src/main/java/com/graphy/backend/domain/comment/dto/response/GetReplyListResponse.java
  backend/src/main/java/com/graphy/backend/domain/comment/repository/CommentCustomRepository.java
  backend/src/main/java/com/graphy/backend/domain/comment/repository/CommentCustomRepositoryImpl.java
  backend/src/main/java/com/graphy/backend/domain/comment/repository/CommentRepository.java
  backend/src/main/java/com/graphy/backend/domain/comment/service/CommentService.java
  backend/src/main/java/com/graphy/backend/domain/project/controller/ProjectController.java
  backend/src/main/java/com/graphy/backend/domain/project/domain/Project.java
  backend/src/main/java/com/graphy/backend/domain/project/dto/ProjectDto.java
  backend/src/main/java/com/graphy/backend/domain/project/dto/response/GetProjectDetailResponse.java
  backend/src/main/java/com/graphy/backend/domain/project/mapper/ProjectMapper.java
  backend/src/main/java/com/graphy/backend/domain/project/service/ProjectService.java
  backend/src/test/java/com/graphy/backend/domain/comment/controller/CommentControllerTest.java
  backend/src/test/java/com/graphy/backend/domain/comment/repository/CommentRepositoryTest.java
  backend/src/test/java/com/graphy/backend/domain/comment/service/CommentServiceTest.java
  backend/src/test/java/com/graphy/backend/domain/member/controller/MemberControllerTest.java
  backend/src/test/java/com/graphy/backend/domain/project/controller/ProjectControllerTest.java
  backend/src/test/java/com/graphy/backend/domain/project/service/ProjectServiceTest.java
  backend/src/test/java/com/graphy/backend/test/MockApiTest.java
Labels: 리팩토링

#193 Be/#191 Member 도메인 리팩토링
  backend/src/main/java/com/graphy/backend/domain/auth/controller/AuthController.java
  backend/src/main/java/com/graphy/backend/domain/auth/controller/JwtFilter.java
  backend/src/main/java/com/graphy/backend/domain/auth/domain/RefreshToken.java
  backend/src/main/java/com/graphy/backend/domain/auth/dto/request/LogoutRequest.java
  backend/src/main/java/com/graphy/backend/domain/auth/dto/response/GetTokenInfoResponse.java
  backend/src/main/java/com/graphy/backend/domain/auth/infra/TokenProvider.java
  backend/src/main/java/com/graphy/backend/domain/auth/repository/RefreshTokenRepository.java
  backend/src/main/java/com/graphy/backend/domain/auth/service/AuthService.java
  backend/src/main/java/com/graphy/backend/domain/auth/service/CustomUserDetailsService.java
  backend/src/main/java/com/graphy/backend/domain/auth/util/MemberInfo.java
  backend/src/main/java/com/graphy/backend/domain/auth/util/annotation/CurrentUser.java
  backend/src/main/java/com/graphy/backend/domain/comment/controller/CommentController.java
  backend/src/main/java/com/graphy/backend/domain/comment/repository/CommentCustomRepository.java
  backend/src/main/java/com/graphy/backend/domain/follow/controller/FollowController.java
  backend/src/main/java/com/graphy/backend/domain/follow/repository/FollowRepository.java
  backend/src/main/java/com/graphy/backend/domain/follow/service/FollowService.java
  backend/src/main/java/com/graphy/backend/domain/member/controller/MemberController.java
  backend/src/main/java/com/graphy/backend/domain/member/domain/Member.java
  backend/src/main/java/com/graphy/backend/domain/member/dto/MemberDto.java
  backend/src/main/java/com/graphy/backend/domain/member/dto/MemberListDto.java
  backend/src/main/java/com/graphy/backend/domain/member/dto/request/SignInMemberRequest.java
  backend/src/main/java/com/graphy/backend/domain/member/dto/request/SignUpMemberRequest.java
  backend/src/main/java/com/graphy/backend/domain/member/dto/response/GetMemberListResponse.java
  backend/src/main/java/com/graphy/backend/domain/member/dto/response/GetMemberResponse.java
  backend/src/main/java/com/graphy/backend/domain/member/dto/response/GetMyPageResponse.java
  backend/src/main/java/com/graphy/backend/domain/member/repository/MemberCustomRepository.java
  backend/src/main/java/com/graphy/backend/domain/member/repository/MemberCustomRepositoryImpl.java
  backend/src/main/java/com/graphy/backend/domain/member/repository/MemberRepository.java
  backend/src/main/java/com/graphy/backend/domain/member/service/MemberService.java
  backend/src/main/java/com/graphy/backend/domain/project/controller/ProjectController.java
  backend/src/main/java/com/graphy/backend/domain/project/domain/Like.java
  backend/src/main/java/com/graphy/backend/domain/project/dto/response/GetProjectDetailResponse.java
  backend/src/main/java/com/graphy/backend/domain/project/dto/response/GetProjectResponse.java
  backend/src/main/java/com/graphy/backend/domain/project/repository/LikeRepository.java
  backend/src/main/java/com/graphy/backend/domain/project/service/LikeService.java
  backend/src/main/java/com/graphy/backend/domain/project/service/ProjectService.java
  backend/src/main/java/com/graphy/backend/global/auth/jwt/dto/TokenDto.java
  backend/src/main/java/com/graphy/backend/global/common/Helper.java
  backend/src/main/java/com/graphy/backend/global/config/SecurityConfig.java
  backend/src/main/java/com/graphy/backend/global/error/ErrorCode.java
  backend/src/main/java/com/graphy/backend/global/error/exception/InvalidTokenException.java
  backend/src/main/java/com/graphy/backend/global/result/ResultCode.java
  backend/src/test/java/com/graphy/backend/domain/auth/controller/AuthControllerTest.java
  backend/src/test/java/com/graphy/backend/domain/auth/service/AuthServiceTest.java
  backend/src/test/java/com/graphy/backend/domain/auth/service/CustomUserDetailsServiceTest.java
  backend/src/test/java/com/graphy/backend/domain/comment/repository/CommentRepositoryTest.java
  backend/src/test/java/com/graphy/backend/domain/follow/controller/FollowControllerTest.java
  backend/src/test/java/com/graphy/backend/domain/follow/service/FollowServiceTest.java
  backend/src/test/java/com/graphy/backend/domain/job/controller/JobControllerTest.java
  backend/src/test/java/com/graphy/backend/domain/member/controller/MemberControllerTest.java
  backend/src/test/java/com/graphy/backend/domain/member/repository/MemberRepositoryTest.java
  backend/src/test/java/com/graphy/backend/domain/member/service/MemberServiceTest.java
  backend/src/test/java/com/graphy/backend/domain/project/controller/ProjectControllerTest.java
  backend/src/test/java/com/graphy/backend/domain/project/controller/ProjectIntegrationTest.java
  backend/src/test/java/com/graphy/backend/domain/project/service/ProjectServiceTest.java
  backend/src/test/java/com/graphy/backend/test/MockApiTest.java
Labels: 리팩토링
