Repository techeer-sv/graphy, pull requests merged in 2023-09, with the labels that each got.

#195 BE/#194 Like 도메인 리팩토링
  backend/Dockerfile
  backend/src/main/java/com/graphy/backend/domain/auth/service/CustomUserDetailsService.java
  backend/src/main/java/com/graphy/backend/domain/follow/controller/FollowController.java
  backend/src/main/java/com/graphy/backend/domain/follow/repository/FollowCustomRepository.java
  backend/src/main/java/com/graphy/backend/domain/follow/repository/FollowRepository.java
  backend/src/main/java/com/graphy/backend/domain/follow/repository/custom/FollowCustomRepositoryImpl.java
  backend/src/main/java/com/graphy/backend/domain/follow/service/FollowService.java
  backend/src/main/java/com/graphy/backend/domain/member/dto/response/GetMemberListResponse.java
  backend/src/main/java/com/graphy/backend/domain/project/controller/LikeController.java
  backend/src/main/java/com/graphy/backend/domain/project/domain/Project.java
  backend/src/main/java/com/graphy/backend/domain/project/repository/LikeCustomRepository.java
  backend/src/main/java/com/graphy/backend/domain/project/repository/LikeRepository.java
  backend/src/main/java/com/graphy/backend/domain/project/repository/custom/LikeCustomRepositoryImpl.java
  backend/src/main/java/com/graphy/backend/domain/project/repository/custom/ProjectCustomRepositoryImpl.java
  backend/src/main/java/com/graphy/backend/domain/project/service/LikeService.java
  backend/src/main/java/com/graphy/backend/global/result/ResultCode.java
  backend/src/test/java/com/graphy/backend/domain/follow/controller/FollowControllerTest.java
  backend/src/test/java/com/graphy/backend/domain/follow/domain/FollowTest.java
  backend/src/test/java/com/graphy/backend/domain/follow/service/FollowServiceTest.java
  backend/src/test/java/com/graphy/backend/domain/member/service/MemberServiceTest.java
  backend/src/test/java/com/graphy/backend/domain/project/service/ProjectServiceTest.java
Labels: 리팩토링

#197 BE/#196 Spring REST Docs 세팅
  .gitignore
  backend/build.gradle
  backend/src/docs/asciidoc/auth.adoc
  backend/src/docs/asciidoc/comment.adoc
  backend/src/docs/asciidoc/follow.adoc
  backend/src/docs/asciidoc/index.adoc
  backend/src/docs/asciidoc/member.adoc
  backend/src/docs/asciidoc/project.adoc
  backend/src/main/java/com/graphy/backend/global/config/ChatGPTConfig.java
  backend/src/test/java/com/graphy/backend/BackendApplicationTests.java
  backend/src/test/java/com/graphy/backend/domain/auth/controller/AuthControllerTest.java
  backend/src/test/java/com/graphy/backend/domain/comment/controller/CommentControllerTest.java
  backend/src/test/java/com/graphy/backend/test/config/ApiDocumentUtil.java
  docker-compose.yml
Labels: 기타/세팅

#200 BE/#199 수정, 삭제 API 상태 코드 변경
  backend/src/main/java/com/graphy/backend/domain/auth/controller/AuthController.java
  backend/src/main/java/com/graphy/backend/domain/comment/controller/CommentController.java
  backend/src/main/java/com/graphy/backend/domain/follow/controller/FollowController.java
  backend/src/main/java/com/graphy/backend/domain/project/controller/ProjectController.java
  backend/src/main/java/com/graphy/backend/domain/project/service/ProjectService.java
  backend/src/test/java/com/graphy/backend/domain/auth/controller/AuthControllerTest.java
  backend/src/test/java/com/graphy/backend/domain/comment/controller/CommentControllerTest.java
Labels: 리팩토링

#202 BE/#201 Comment 도메인 QueryDSL 리팩토링
  backend/src/main/java/com/graphy/backend/domain/comment/dto/response/GetCommentWithMaskingResponse.java
  backend/src/main/java/com/graphy/backend/domain/comment/dto/response/GetReplyListResponse.java
  backend/src/main/java/com/graphy/backend/domain/comment/repository/CommentCustomRepository.java
  backend/src/main/java/com/graphy/backend/domain/comment/repository/CommentCustomRepositoryImpl.java
  backend/src/main/java/com/graphy/backend/domain/comment/service/CommentService.java
  backend/src/main/java/com/graphy/backend/domain/project/dto/request/CreateProjectRequest.java
  backend/src/test/java/com/graphy/backend/domain/comment/repository/CommentRepositoryTest.java
  backend/src/test/java/com/graphy/backend/domain/comment/service/CommentServiceTest.java
Labels: 리팩토링

#205 BE/#203 팔로우, 프로젝트 테스트 수정
  backend/src/main/java/com/graphy/backend/domain/follow/service/FollowService.java
  backend/src/main/java/com/graphy/backend/domain/project/dto/response/UpdateProjectResponse.java
  backend/src/test/java/com/graphy/backend/domain/follow/controller/FollowControllerTest.java
  backend/src/test/java/com/graphy/backend/domain/follow/service/FollowServiceTest.java
  backend/src/test/java/com/graphy/backend/domain/job/controller/JobControllerTest.java
  backend/src/test/java/com/graphy/backend/domain/member/controller/MemberControllerTest.java
  backend/src/test/java/com/graphy/backend/domain/project/controller/ProjectControllerTest.java
  backend/src/test/java/com/graphy/backend/domain/project/controller/ProjectIntegrationTest.java
  backend/src/test/java/com/graphy/backend/domain/project/service/ProjectServiceTest.java
Labels: 리팩토링, 테스트

#210 BE/#209 controller mock mvc 테스트를 위한 userdetails 설정
  backend/src/test/java/com/graphy/backend/domain/follow/controller/FollowControllerTest.java
  backend/src/test/java/com/graphy/backend/domain/member/controller/MemberControllerTest.java
  backend/src/test/java/com/graphy/backend/domain/project/controller/ProjectControllerTest.java
  backend/src/test/java/com/graphy/backend/test/security/WithMockCustomUserSecurityContextFactory.java
  backend/src/test/java/com/graphy/backend/test/util/WithMockCustomUser.java
Labels: 리팩토링, 테스트

#216 BE/#211 팔로잉 피드 조회 기능 구현
  backend/src/main/java/com/graphy/backend/domain/member/controller/MemberController.java
  backend/src/main/java/com/graphy/backend/domain/member/service/MemberService.java
  backend/src/main/java/com/graphy/backend/domain/project/controller/ProjectController.java
  backend/src/main/java/com/graphy/backend/domain/project/repository/ProjectCustomRepository.java
  backend/src/main/java/com/graphy/backend/domain/project/repository/custom/ProjectCustomRepositoryImpl.java
  backend/src/main/java/com/graphy/backend/domain/project/service/ProjectService.java
  backend/src/test/java/com/graphy/backend/domain/member/controller/MemberControllerTest.java
  backend/src/test/java/com/graphy/backend/domain/member/service/MemberServiceTest.java
  backend/src/test/java/com/graphy/backend/domain/project/service/ProjectServiceTest.java
Labels: 기능구현

#217 Fe/#214 로그인 페이지 마이그레이션
  .github/workflows/CI.yml
  frontend/.eslintrc.json
  frontend/package.json
  frontend/src/app/(user)/login/error.tsx
  frontend/src/app/(user)/login/page.tsx
  frontend/src/app/global-error.tsx
  frontend/src/app/globals.css
  frontend/src/app/page.tsx
  frontend/src/utils/atoms.ts
  frontend/tailwind.config.cjs
  frontend/tailwind.config.ts
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: 기능구현

#213 chore : 프로젝트 구인 게시글 도메인 초기 세팅
  backend/src/main/java/com/graphy/backend/domain/bookmark/domain/Bookmark.java
  backend/src/main/java/com/graphy/backend/domain/comment/domain/Comment.java
  backend/src/main/java/com/graphy/backend/domain/follow/domain/Follow.java
  backend/src/main/java/com/graphy/backend/domain/message/controller/MessageController.java
  backend/src/main/java/com/graphy/backend/domain/message/domain/Message.java
  backend/src/main/java/com/graphy/backend/domain/message/repository/MessageRepository.java
  backend/src/main/java/com/graphy/backend/domain/message/service/MessageService.java
  backend/src/main/java/com/graphy/backend/domain/project/domain/Project.java
  backend/src/main/java/com/graphy/backend/domain/project/domain/ProjectTag.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/controller/ApplicationController.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/controller/RecruitmentController.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/domain/Application.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/domain/ApplicationTag.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/domain/ApplicationTags.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/domain/Position.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/domain/ProcessType.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/domain/Recruitment.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/domain/RecruitmentTag.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/domain/RecruitmentTags.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/repository/ApplicationRepository.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/repository/RecruitmentRepository.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/service/ApplicationService.java
  backend/src/main/java/com/graphy/backend/domain/recruitment/service/RecruitmentService.java
Labels: 기타/세팅

#221 BE/#220 testcontainers를 적용한 통합 테스트 환경 세팅
  .gitignore
  backend/build.gradle
  backend/src/test/java/com/graphy/backend/domain/comment/repository/CommentRepositoryTest.java
  backend/src/test/java/com/graphy/backend/domain/follow/repository/FollowRepositoryTest.java
  backend/src/test/java/com/graphy/backend/domain/member/repository/MemberRepositoryTest.java
  backend/src/test/java/com/graphy/backend/domain/project/controller/ProjectControllerTest.java
  backend/src/test/java/com/graphy/backend/domain/project/controller/ProjectIntegrationTest.java
  backend/src/test/java/com/graphy/backend/test/MockApiTest.java
  backend/src/test/java/com/graphy/backend/test/MockTest.java
  backend/src/test/java/com/graphy/backend/test/config/TestProfile.java
  backend/src/test/java/com/graphy/backend/test/util/IntegrationTest.java
  backend/src/test/resources/application-unit.yml
  backend/src/test/resources/logback-test.xml
  backend/src/test/resources/schema.sql
Labels: 기타/세팅, 테스트

#227 FE/#215 메인 페이지, ProjectCard 마이그레이션
  backend/src/test/java/com/graphy/backend/domain/follow/controller/FollowControllerTest.java
  backend/src/test/java/com/graphy/backend/domain/member/controller/MemberControllerTest.java
  backend/src/test/java/com/graphy/backend/domain/project/controller/ProjectControllerTest.java
  backend/src/test/java/com/graphy/backend/test/security/WithMockCustomUserSecurityContextFactory.java
  backend/src/test/java/com/graphy/backend/test/util/WithMockCustomUser.java
  frontend/package.json
  frontend/src/app/layout.tsx
  frontend/src/app/page.tsx
  frontend/src/components/general/Provider.tsx
  frontend/src/components/main/Banner.tsx
  frontend/src/components/main/ProjectCard.tsx
  frontend/src/utils/atoms.ts
  frontend/src/utils/recoilRootProvider.tsx
  frontend/yarn.lock
Labels: 기능구현

#230 feat : 유저 검색 페이지 마이그레이션
  frontend/package.json
  frontend/src/app/(search)/search-user/[nickname]/page.tsx
  frontend/src/app/(search)/search-user/page.tsx
  frontend/yarn.lock
Labels: 기능구현

#226 fix: findList API 변경으로 인한 SecurityConfig 변경
  backend/src/main/java/com/graphy/backend/global/config/SecurityConfig.java
Labels: 오류 수정
