Repository techeer-sv/graphy, pull requests merged in 2023-05, with the labels that each got.

#89 BE/#88 테스트 코드 수정
  backend/src/test/java/com/graphy/backend/BackendApplicationTests.java
  backend/src/test/java/com/graphy/backend/domain/project/controller/ProjectIntegrationTest.java
  frontend/src/assets/image/stacklogo/JavaScript.svg
  frontend/src/assets/image/stacklogo/TensorFlow.svg
Labels: 오류 수정

#96 Be/#94 답글 조회 API 구현 및 테스트 코드 작성
  .github/workflows/CI.yml
  backend/src/main/java/com/graphy/backend/domain/comment/controller/CommentController.java
  backend/src/main/java/com/graphy/backend/domain/comment/dto/CommentWithMaskingDto.java
  backend/src/main/java/com/graphy/backend/domain/comment/dto/ReplyListDto.java
  backend/src/main/java/com/graphy/backend/domain/comment/repository/CommentRepository.java
  backend/src/main/java/com/graphy/backend/domain/comment/service/CommentService.java
  backend/src/main/java/com/graphy/backend/domain/project/dto/ProjectDto.java
  backend/src/main/java/com/graphy/backend/domain/project/mapper/ProjectMapper.java
  backend/src/main/java/com/graphy/backend/domain/project/service/ProjectService.java
  backend/src/main/java/com/graphy/backend/global/result/ResultCode.java
  backend/src/test/java/com/graphy/backend/domain/comment/controller/CommentControllerTest.java
  backend/src/test/java/com/graphy/backend/domain/project/controller/ProjectControllerTest.java
  backend/src/test/java/com/graphy/backend/domain/project/service/ProjectServiceTest.java
Labels: 기능구현

#99 Fe/#90 댓글 api 변경 적용
  frontend/package-lock.json
  frontend/src/components/PutReply.tsx
  frontend/src/components/ReadReReply.tsx
  frontend/src/components/ReadReply.tsx
  frontend/src/components/Reply.tsx
  frontend/src/components/WriteReReply.tsx
  frontend/src/index.css
  frontend/src/pages/MainPage.tsx
  frontend/src/useDidMountEffect.tsx
  frontend/yarn.lock
Labels: 기능구현

#100 BE/#92 chatGPT 세팅
  backend/build.gradle
  backend/src/main/java/com/graphy/backend/domain/project/controller/ProjectController.java
  backend/src/main/java/com/graphy/backend/global/chatgpt/dto/GptCompletionDto.java
  backend/src/main/java/com/graphy/backend/global/chatgpt/service/GPTChatRestService.java
  backend/src/main/java/com/graphy/backend/global/config/ChatGPTConfig.java
  backend/src/main/java/com/graphy/backend/global/result/ResultCode.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/graphy/backend/domain/project/controller/ProjectControllerTest.java
  backend/src/test/java/com/graphy/backend/domain/project/service/ProjectServiceTest.java
  backend/src/test/java/com/graphy/backend/test/MockApiTest.java
  backend/src/test/java/com/graphy/backend/test/MockTest.java
Labels: 기타/세팅

#102 BE/#101 custom PageRequest 적용
  backend/src/main/java/com/graphy/backend/domain/project/controller/ProjectController.java
  backend/src/main/java/com/graphy/backend/global/common/PageRequest.java
  backend/src/test/java/com/graphy/backend/domain/project/controller/ProjectControllerTest.java
Labels: 리팩토링

#105 BE/#104 chatGPT 연결 및 기능 구현
  backend/src/main/java/com/graphy/backend/domain/project/controller/ProjectController.java
  backend/src/main/java/com/graphy/backend/domain/project/dto/ProjectDto.java
  backend/src/main/java/com/graphy/backend/domain/project/service/ProjectService.java
  backend/src/main/java/com/graphy/backend/global/chatgpt/dto/GptCompletionDto.java
  backend/src/main/java/com/graphy/backend/global/config/AsyncConfig.java
  backend/src/main/java/com/graphy/backend/global/config/ChatGPTConfig.java
  backend/src/main/java/com/graphy/backend/global/error/ErrorCode.java
  backend/src/main/java/com/graphy/backend/global/error/GlobalExceptionHandler.java
  backend/src/main/java/com/graphy/backend/global/error/exception/LongRequestException.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/graphy/backend/BackendApplicationTests.java
  backend/src/test/java/com/graphy/backend/domain/project/controller/ProjectControllerTest.java
Labels: 기능구현

#110 Fe/#95 PWA적용
  frontend/index.html
  frontend/manifest.json
  frontend/package-lock.json
  frontend/package.json
  frontend/service-worker.js
  frontend/src/App.tsx
  frontend/src/assets/image/icon/192.png
  frontend/src/assets/image/icon/512.png
  frontend/src/assets/image/icon/96.png
  frontend/src/assets/image/icon/screenshot.png
  frontend/src/components/ImageUploader.tsx
  frontend/src/components/LoadingSpinner.tsx
  frontend/src/components/NavBar.tsx
  frontend/src/components/ProjectCard.tsx
  frontend/src/components/PutReply.tsx
  frontend/src/components/QuillEditor.tsx
  frontend/src/components/ReadReReply.tsx
  frontend/src/components/ReadReply.tsx
  frontend/src/components/Reply.tsx
  frontend/src/components/WriteReReply.tsx
  frontend/src/index.css
  frontend/src/pages/ErrorPage.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/ModifyingPage.tsx
  frontend/src/pages/ReadingPage.tsx
  frontend/src/pages/WritingPage.tsx
  frontend/yarn.lock
  nginx/nginx.conf
Labels: 기능구현

#109 refactor:ELK 세팅 수정
  .gitignore
  backend/.gitignore
  backend/build.gradle
  docker-compose.logging.yml
  docker-compose.yml
  logging-example/elasticsearch/.dockerignore
  logging-example/elasticsearch/Dockerfile
  logging-example/elasticsearch/config/elasticsearch.yml
  logging-example/filebeat/.dockerignore
  logging-example/filebeat/Dockerfile
  logging-example/filebeat/config/filebeat.yml
  logging-example/kibana/.dockerignore
  logging-example/kibana/Dockerfile
  logging-example/kibana/config/kibana.yml
  logging-example/logstash/.dockerignore
  logging-example/logstash/Dockerfile
  logging-example/logstash/config/logstash.yml
  logging-example/logstash/pipeline/logstash.conf
Labels: 리팩토링

#117 Fe/#116 글 작성 페이지 테스트
  README.md
  frontend/jest.config.cjs
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/ImageUploader.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/test/components/ImageUploader.test.tsx
  frontend/src/test/components/NavBar.test.tsx
  frontend/src/test/components/ProjectCard.test.tsx
  frontend/src/test/components/QuillEditor.test.tsx
  frontend/src/test/components/TechStackSelection.test.tsx
  frontend/src/test/jest/RecoilObserver.tsx
  frontend/src/test/jest/setupFile.js
  frontend/src/test/pages/MainPage.test.tsx
  frontend/src/test/pages/ModifyingPage.test.tsx
  frontend/src/test/pages/WritingPage.test.tsx
  frontend/yarn.lock
Labels: 테스트

#119 Fe/#118 글 상세조회 페이지 테스트
  .env.example
  frontend/.dockerignore
  frontend/.env.example
  frontend/.eslintrc
  frontend/.eslintrc.js
  frontend/.gitignore
  frontend/Dockerfile
  frontend/jest.config.cjs
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/Stack.tsx
  frontend/src/assets/lottie.tsx
  frontend/src/assets/lottie/developer.json
  frontend/src/components/Banner.tsx
  frontend/src/components/ImageUploader.tsx
  frontend/src/components/LoadingSpinner.tsx
  frontend/src/components/NavBar.tsx
  frontend/src/components/ProjectCard.tsx
  frontend/src/components/PutReply.tsx
  frontend/src/components/QuillEditor.tsx
  frontend/src/components/QuillWritten.tsx
  frontend/src/components/ReadReReply.tsx
  frontend/src/components/ReadReply.tsx
  frontend/src/components/Reply.tsx
  frontend/src/components/TechStackSelection.tsx
  frontend/src/components/WriteReReply.tsx
  frontend/src/main.tsx
  frontend/src/pages/ErrorPage.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/ModifyingPage.tsx
  frontend/src/pages/ReadingPage.tsx
  frontend/src/pages/WritingPage.tsx
  frontend/src/test/components/Banner.test.tsx
  frontend/src/test/components/ImageUploader.test.tsx
  frontend/src/test/components/LoadingSpinner.test.tsx
  frontend/src/test/components/NavBar.test.tsx
  frontend/src/test/components/ProjectCard.test.tsx
  frontend/src/test/components/PutReply.test.tsx
  frontend/src/test/components/QuillEditor.test.tsx
  frontend/src/test/components/QuillWritten.test.tsx
  frontend/src/test/components/ReadReReply.test.tsx
  frontend/src/test/components/ReadReply.test.tsx
  frontend/src/test/components/Reply.test.tsx
  frontend/src/test/components/TechStackSelection.test.tsx
  frontend/src/test/components/WriteReReply.test.tsx
  frontend/src/test/jest/RecoilObserver.tsx
  frontend/src/test/jest/__mocks__/fileTransform.js
  frontend/src/test/jest/setupFile.js
  frontend/src/test/pages/ErrorPage.test.tsx
  frontend/src/test/pages/MainPage.test.tsx
  frontend/src/test/pages/ModifyingPage.test.tsx
  frontend/src/test/pages/ReadingPage.test.tsx
  frontend/src/test/pages/WritingPage.test.tsx
  frontend/tsconfig.json
  frontend/vite.config.ts
  frontend/yarn.lock
Labels: 테스트
